name: Bug Report
description: 🐞 Report a bug in signalstory
title: '[Bug report]'
labels:
  - bug
assignees: zuriscript
body:
  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: If possible, provide a link to a minimal reproduction of the bug

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: environment
    attributes:
      label: Please provide the environment you discovered this bug in
      render: true

  - type: textarea
    id: other
    attributes:
      label: Anything else?

  - type: dropdown
    id: contribute
    attributes:
      label: Do you want to create a pull request?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
